const TaskKanban = [
  {
    todo: [
      {
        id: 1,
        title: "Design sistem inventory baru",
        description:
          "Membuat wireframe dan mockup untuk sistem inventory perusahaan",
        priority: "high",
        assignee: { name: "Sarah K", avatar: "SK" },
        dueDate: "2024-08-05",
        tags: ["design", "inventory"],
        comments: 3,
        attachments: 2,
      },
      {
        id: 2,
        title: "Review dokumentasi API",
        description: "Melakukan review dan update dokumentasi API existing",
        priority: "medium",
        assignee: { name: "Ahmad R", avatar: "AR" },
        dueDate: "2024-08-03",
        tags: ["development", "documentation"],
        comments: 1,
        attachments: 0,
      },
      {
        id: 3,
        title: "Setup testing environment",
        description: "Konfigurasi environment untuk automated testing",
        priority: "low",
        assignee: { name: "Budi S", avatar: "BS" },
        dueDate: "2024-08-10",
        tags: ["testing", "devops"],
        comments: 0,
        attachments: 1,
      },
    ],
    inprogress: [
      {
        id: 4,
        title: "Implementasi fitur login SSO",
        description: "Integrasi dengan Active Directory untuk single sign-on",
        priority: "high",
        assignee: { name: "Dewi L", avatar: "DL" },
        dueDate: "2024-07-30",
        tags: ["development", "security"],
        comments: 5,
        attachments: 3,
      },
      {
        id: 5,
        title: "Optimasi database query",
        description: "Improve performance untuk query yang lambat",
        priority: "medium",
        assignee: { name: "Eko P", avatar: "EP" },
        dueDate: "2024-08-01",
        tags: ["database", "performance"],
        comments: 2,
        attachments: 1,
      },
    ],
    done: [
      {
        id: 6,
        title: "Migrasi data customer",
        description: "Memindahkan data customer ke database baru",
        priority: "high",
        assignee: { name: "Fitri M", avatar: "FM" },
        dueDate: "2024-07-25",
        tags: ["migration", "database"],
        comments: 8,
        attachments: 4,
      },
      {
        id: 7,
        title: "Training team development",
        description: "Pelatihan framework terbaru untuk tim development",
        priority: "medium",
        assignee: { name: "Gani H", avatar: "GH" },
        dueDate: "2024-07-20",
        tags: ["training", "development"],
        comments: 12,
        attachments: 0,
      },
    ],
  },
];

export default TaskKanban;
