const TeamMembers = [
  {
    id: 1,
    name: "Sarah Kusuma",
    email: "sarah.kusuma@pkc.com",
    phone: "+62 812-3456-7890",
    position: "Frontend Developer",
    department: "IT Development",
    role: "Admin",
    status: "active",
    avatar: "SK",
    joinDate: "2023-01-15",
    lastActive: "2024-07-30 14:30",
    tasksCompleted: 42,
    tasksInProgress: 3,
    meetingsAttended: 18,
    location: "Jakarta",
    skills: ["React", "TypeScript", "UI/UX Design"],
  },
  {
    id: 2,
    name: "Ahmad Rahman",
    email: "ahmad.rahman@pkc.com",
    phone: "+62 813-4567-8901",
    position: "Backend Developer",
    department: "IT Development",
    role: "Manager",
    status: "active",
    avatar: "AR",
    joinDate: "2022-08-20",
    lastActive: "2024-07-30 16:45",
    tasksCompleted: 38,
    tasksInProgress: 5,
    meetingsAttended: 22,
    location: "Bandung",
    skills: ["Node.js", "PostgreSQL", "API Design"],
  },
  {
    id: 3,
    name: "Budi Santoso",
    email: "budi.santoso@pkc.com",
    phone: "+62 814-5678-9012",
    position: "DevOps Engineer",
    department: "IT Infrastructure",
    role: "Employee",
    status: "active",
    avatar: "BS",
    joinDate: "2023-05-10",
    lastActive: "2024-07-30 13:20",
    tasksCompleted: 29,
    tasksInProgress: 2,
    meetingsAttended: 14,
    location: "Jakarta",
    skills: ["Docker", "Kubernetes", "AWS"],
  },
  {
    id: 4,
    name: "Dewi Lestari",
    email: "dewi.lestari@pkc.com",
    phone: "+62 815-6789-0123",
    position: "Security Specialist",
    department: "IT Security",
    role: "Manager",
    status: "active",
    avatar: "DL",
    joinDate: "2022-03-01",
    lastActive: "2024-07-30 15:10",
    tasksCompleted: 35,
    tasksInProgress: 4,
    meetingsAttended: 20,
    location: "Surabaya",
    skills: ["Cybersecurity", "Penetration Testing", "SIEM"],
  },
  {
    id: 5,
    name: "Eko Prasetyo",
    email: "eko.prasetyo@pkc.com",
    phone: "+62 816-7890-1234",
    position: "Database Administrator",
    department: "IT Infrastructure",
    role: "Employee",
    status: "inactive",
    avatar: "EP",
    joinDate: "2023-09-15",
    lastActive: "2024-07-28 09:30",
    tasksCompleted: 18,
    tasksInProgress: 1,
    meetingsAttended: 8,
    location: "Jakarta",
    skills: ["MySQL", "MongoDB", "Data Analytics"],
  },
  {
    id: 6,
    name: "Fitri Maharani",
    email: "fitri.maharani@pkc.com",
    phone: "+62 817-8901-2345",
    position: "Project Manager",
    department: "Project Management",
    role: "Manager",
    status: "active",
    avatar: "FM",
    joinDate: "2021-11-05",
    lastActive: "2024-07-30 17:00",
    tasksCompleted: 56,
    tasksInProgress: 8,
    meetingsAttended: 45,
    location: "Jakarta",
    skills: ["Agile", "Scrum", "Leadership"],
  },
  {
    id: 7,
    name: "Abedul bedul",
    email: "abedul@pkc.com",
    phone: "+62 817-8696-2345",
    position: "Fulstek menejer",
    department: "Biro TI",
    role: "Team Leader",
    status: "active",
    avatar: "AB",
    joinDate: "2023-11-05",
    lastActive: "2024-07-30 17:00",
    tasksCompleted: 1,
    tasksInProgress: 50,
    meetingsAttended: 10,
    location: "Cikampek",
    skills: ["Ngoding", "Emote", "Leadership"],
  },
  {
    id: 9,
    name: "Ajmoy jamoy",
    email: "ajemoy@pkc.com",
    phone: "+62 817-0987-2345",
    position: "Beckend staff",
    department: "Biro TI",
    role: "Employee",
    status: "active",
    avatar: "AJ",
    joinDate: "2024-05-05",
    lastActive: "2024-07-30 17:00",
    tasksCompleted: 1,
    tasksInProgress: 90,
    meetingsAttended: 12,
    location: "Cikampek",
    skills: ["Ngoding", "Java", "Mangan"],
  },
  {
    id: 10,
    name: "Rehuy Jahuy",
    email: "Rejaw@pkc.com",
    phone: "+62 817-7865-2345",
    position: "UI/UX Designer",
    department: "Biro TI",
    role: "Employee",
    status: "active",
    avatar: "RJ",
    joinDate: "2024-06-05",
    lastActive: "2024-07-30 17:00",
    tasksCompleted: 2,
    tasksInProgress: 30,
    meetingsAttended: 20,
    location: "Cikampek",
    skills: ["Toksik", "Figma", "Java"],
  },
  {
    id: 11,
    name: "Radya",
    email: "Radya@pkc.com",
    phone: "+62 817-1515-2345",
    position: "Menejer",
    department: "Biro TI",
    role: "Manager",
    status: "active",
    avatar: "RH",
    joinDate: "2021-06-05",
    lastActive: "2024-07-30 17:00",
    tasksCompleted: 90,
    tasksInProgress: 5,
    meetingsAttended: 75,
    location: "Cikampek",
    skills: ["Friendly", "Ramah", "The Best"],
  },
];

export default TeamMembers;
